{% set name = "kartograf" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kartograf-{{ version }}.tar.gz
  sha256: 0c769d0da80fd8fee1b012434c720399cab5457e728c4fda534a9145fcba0560

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0
    - versioningit
  run:
    - networkx
    - numpy
    - python >=3.9
    - rdkit
    - scipy
    - gufe

test:
  imports:
    - kartograf
  requires:
    - pip

about:
  home: https://github.com/OpenFreeEnergy/kartograf
  summary: This is a package for setting up FE-calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
