{% set name = "kartograf" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit
  run:
    - dill
    - gufe >=1.0
    - numpy
    - py3Dmol
    - python >={{ python_min }}
    - rdkit
    - scipy

test:
  imports:
    - kartograf
  source_files:
    - src/kartograf/tests/data/2wtk_mutated_with_extra_mols.pdb
    - src/kartograf/tests/data/2wtk_trimer_with_extra_mols.pdb
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pytest --pyargs kartograf

about:
  home: https://github.com/OpenFreeEnergy/kartograf
  summary: Kartograf is a package for mapping geometrically atoms of two molecules. (like you need it with hybrid topology)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
