schema_version: 1

context:
  owner: "OpenFreeEnergy" 
  name: kartograf
  version: "2.0.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ owner }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f1afff568478f287f48216ab5655b7253e85bd07008155f608e046f763f89ff2

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - versioningit
  run:
    - dill
    - gufe >=1.11
    - numpy
    - python >=${{ python_min }}
    - rdkit
    - scipy

tests:
  - python:
      imports:
        - kartograf
      pip_check: false
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - pytest
        - python ${{ python_min }}.*
        - py3Dmol
        - ipywidgets
    script:
      - pytest --pyargs kartograf

about:
  summary: Kartograf is a package for mapping geometrically atoms of two molecules. (like you need it with hybrid topology)
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/OpenFreeEnergy/kartograf

extra:
  recipe-maintainers:
    - jthorton
    - hannahbaumann
    - atravitz
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
